name: Docker Image CI

on:
  push:
    branches: [ test* ]


jobs:

  build:

    runs-on: ubuntu-latest
    env:
      UA_VERSION: 22.3.1

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

#    - name: Build the thin Docker image
#      run: docker build ./Dockerfile -t dockerua:thin
        
    - name: Build the full Docker image
      run: docker build -f ./Dockerfile.Full -t dockerua:full